// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CrudOperation.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace WorkorderPackage {
  public static partial class WorkorderService
  {
    static readonly string __ServiceName = "WorkorderPackage.WorkorderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.CreateWorkorderInput> __Marshaller_WorkorderPackage_CreateWorkorderInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.CreateWorkorderInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.CreateWorkorderOutput> __Marshaller_WorkorderPackage_CreateWorkorderOutput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.CreateWorkorderOutput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.ReadWorkorderInput> __Marshaller_WorkorderPackage_ReadWorkorderInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.ReadWorkorderInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.ReadWorkorderOutput> __Marshaller_WorkorderPackage_ReadWorkorderOutput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.ReadWorkorderOutput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.UpdateWorkorderInput> __Marshaller_WorkorderPackage_UpdateWorkorderInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.UpdateWorkorderInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.UpdateWorkorderOutput> __Marshaller_WorkorderPackage_UpdateWorkorderOutput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.UpdateWorkorderOutput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.DeleteWorkorderInput> __Marshaller_WorkorderPackage_DeleteWorkorderInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.DeleteWorkorderInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.DeleteWorkorderOutput> __Marshaller_WorkorderPackage_DeleteWorkorderOutput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.DeleteWorkorderOutput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.ListWorkorderInput> __Marshaller_WorkorderPackage_ListWorkorderInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.ListWorkorderInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WorkorderPackage.ListWorkorderOutput> __Marshaller_WorkorderPackage_ListWorkorderOutput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WorkorderPackage.ListWorkorderOutput.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WorkorderPackage.CreateWorkorderInput, global::WorkorderPackage.CreateWorkorderOutput> __Method_CreateWo = new grpc::Method<global::WorkorderPackage.CreateWorkorderInput, global::WorkorderPackage.CreateWorkorderOutput>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateWo",
        __Marshaller_WorkorderPackage_CreateWorkorderInput,
        __Marshaller_WorkorderPackage_CreateWorkorderOutput);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WorkorderPackage.ReadWorkorderInput, global::WorkorderPackage.ReadWorkorderOutput> __Method_ReadWo = new grpc::Method<global::WorkorderPackage.ReadWorkorderInput, global::WorkorderPackage.ReadWorkorderOutput>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadWo",
        __Marshaller_WorkorderPackage_ReadWorkorderInput,
        __Marshaller_WorkorderPackage_ReadWorkorderOutput);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WorkorderPackage.UpdateWorkorderInput, global::WorkorderPackage.UpdateWorkorderOutput> __Method_UpdateWo = new grpc::Method<global::WorkorderPackage.UpdateWorkorderInput, global::WorkorderPackage.UpdateWorkorderOutput>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateWo",
        __Marshaller_WorkorderPackage_UpdateWorkorderInput,
        __Marshaller_WorkorderPackage_UpdateWorkorderOutput);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WorkorderPackage.DeleteWorkorderInput, global::WorkorderPackage.DeleteWorkorderOutput> __Method_DeleteWo = new grpc::Method<global::WorkorderPackage.DeleteWorkorderInput, global::WorkorderPackage.DeleteWorkorderOutput>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteWo",
        __Marshaller_WorkorderPackage_DeleteWorkorderInput,
        __Marshaller_WorkorderPackage_DeleteWorkorderOutput);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WorkorderPackage.ListWorkorderInput, global::WorkorderPackage.ListWorkorderOutput> __Method_ReadAllWo = new grpc::Method<global::WorkorderPackage.ListWorkorderInput, global::WorkorderPackage.ListWorkorderOutput>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ReadAllWo",
        __Marshaller_WorkorderPackage_ListWorkorderInput,
        __Marshaller_WorkorderPackage_ListWorkorderOutput);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::WorkorderPackage.CrudOperationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WorkorderService</summary>
    [grpc::BindServiceMethod(typeof(WorkorderService), "BindService")]
    public abstract partial class WorkorderServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::WorkorderPackage.CreateWorkorderOutput> CreateWo(global::WorkorderPackage.CreateWorkorderInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::WorkorderPackage.ReadWorkorderOutput> ReadWo(global::WorkorderPackage.ReadWorkorderInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::WorkorderPackage.UpdateWorkorderOutput> UpdateWo(global::WorkorderPackage.UpdateWorkorderInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::WorkorderPackage.DeleteWorkorderOutput> DeleteWo(global::WorkorderPackage.DeleteWorkorderInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ReadAllWo(global::WorkorderPackage.ListWorkorderInput request, grpc::IServerStreamWriter<global::WorkorderPackage.ListWorkorderOutput> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WorkorderService</summary>
    public partial class WorkorderServiceClient : grpc::ClientBase<WorkorderServiceClient>
    {
      /// <summary>Creates a new client for WorkorderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WorkorderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WorkorderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WorkorderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WorkorderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WorkorderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.CreateWorkorderOutput CreateWo(global::WorkorderPackage.CreateWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.CreateWorkorderOutput CreateWo(global::WorkorderPackage.CreateWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.CreateWorkorderOutput> CreateWoAsync(global::WorkorderPackage.CreateWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.CreateWorkorderOutput> CreateWoAsync(global::WorkorderPackage.CreateWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.ReadWorkorderOutput ReadWo(global::WorkorderPackage.ReadWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadWo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.ReadWorkorderOutput ReadWo(global::WorkorderPackage.ReadWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.ReadWorkorderOutput> ReadWoAsync(global::WorkorderPackage.ReadWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadWoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.ReadWorkorderOutput> ReadWoAsync(global::WorkorderPackage.ReadWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.UpdateWorkorderOutput UpdateWo(global::WorkorderPackage.UpdateWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateWo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.UpdateWorkorderOutput UpdateWo(global::WorkorderPackage.UpdateWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.UpdateWorkorderOutput> UpdateWoAsync(global::WorkorderPackage.UpdateWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateWoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.UpdateWorkorderOutput> UpdateWoAsync(global::WorkorderPackage.UpdateWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.DeleteWorkorderOutput DeleteWo(global::WorkorderPackage.DeleteWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WorkorderPackage.DeleteWorkorderOutput DeleteWo(global::WorkorderPackage.DeleteWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.DeleteWorkorderOutput> DeleteWoAsync(global::WorkorderPackage.DeleteWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WorkorderPackage.DeleteWorkorderOutput> DeleteWoAsync(global::WorkorderPackage.DeleteWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteWo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::WorkorderPackage.ListWorkorderOutput> ReadAllWo(global::WorkorderPackage.ListWorkorderInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadAllWo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::WorkorderPackage.ListWorkorderOutput> ReadAllWo(global::WorkorderPackage.ListWorkorderInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ReadAllWo, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override WorkorderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorkorderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(WorkorderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateWo, serviceImpl.CreateWo)
          .AddMethod(__Method_ReadWo, serviceImpl.ReadWo)
          .AddMethod(__Method_UpdateWo, serviceImpl.UpdateWo)
          .AddMethod(__Method_DeleteWo, serviceImpl.DeleteWo)
          .AddMethod(__Method_ReadAllWo, serviceImpl.ReadAllWo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WorkorderServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateWo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WorkorderPackage.CreateWorkorderInput, global::WorkorderPackage.CreateWorkorderOutput>(serviceImpl.CreateWo));
      serviceBinder.AddMethod(__Method_ReadWo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WorkorderPackage.ReadWorkorderInput, global::WorkorderPackage.ReadWorkorderOutput>(serviceImpl.ReadWo));
      serviceBinder.AddMethod(__Method_UpdateWo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WorkorderPackage.UpdateWorkorderInput, global::WorkorderPackage.UpdateWorkorderOutput>(serviceImpl.UpdateWo));
      serviceBinder.AddMethod(__Method_DeleteWo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WorkorderPackage.DeleteWorkorderInput, global::WorkorderPackage.DeleteWorkorderOutput>(serviceImpl.DeleteWo));
      serviceBinder.AddMethod(__Method_ReadAllWo, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::WorkorderPackage.ListWorkorderInput, global::WorkorderPackage.ListWorkorderOutput>(serviceImpl.ReadAllWo));
    }

  }
}
#endregion
